version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=speak
    volumes:
      - ./data/mysql:/var/lib/mysql
  thingspeak:
    image: synomi/thingspeak
    volumes:
      - ./thingspeak/database.yml:/app/thingspeak/config/database.yml
      #- ./thingspeak/environment.rb:/app/thingspeak/config/environment.rb
      #- ./thingspeak/active_admin.rb:/app/thingspeak/config/initializers/active_admin.rb
    ports:
      - "8088:80"
    links:
      - db  
