version: '2'
services:
  db:
    image: postgres:9
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=thingspeak
  thingspeak:
    build: .
    volumes:
      - ./thingspeak/database.yml:/opt/thingspeak/config/database.yml
      - ./thingspeak/environment.rb:/opt/thingspeak/config/environment.rb
      - ./thingspeak/active_admin.rb:/opt/thingspeak/config/initializers/active_admin.rb
    links:
      - db
  web:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=thingspeak.jcu.io
    volumes:
      - ./thingspeak/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    links:
      - thingspeak
    # Explicitly allow $NGINX_HOST variable replacement to avoid conflicts
    # Double-escape the $ because of Docker Compose's variable substitution
    command: >
      /bin/bash -c "envsubst '$${NGINX_HOST}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
